### ISSUE TITLE
16C website C vs c display

### ISSUE THREAD

**Issue by ricknun** [zathras/jrpn#100]
**JRPN 16C or 15C?**
16C

**Describe the bug**
https://jrpn.jovial.com/ shows the 16C with display "cAFE,bAbE".  The c (lowercase) should be a C (capital C) to agree with the real HP-16C and current version of the simulator. 

**Platform:**
Windows 10

**Related Fun**
Years ago I did a got a large file of English words and looked for 4-char hex calc words using the Cygwin/Linux command: cat words.txt | egrep -i "^[AbCdEFOIS]{4}$"
It resulted in this list:
abbe abed aced aces acid adds ados aide aids asea asia baas baba babe
bade bads base bass bead beds beef bees bess bias bibs bide bids biff
bios boas bobs boca bode bods boff boob boos boss cabs cads cafe casa
case ceca cede cees cess ciao cobs coco coda code cods coed coif coos
dabs dace dada dado dads dais dead deaf debs deco deed dees dias dibs
dice dido died dies disc docs dodo does doff dose doss ease ebbs edda
effs eses esse face fade fads feds feed fees fess fibs fica fide fido
fids fief fife fobs foci foes food ibid ibis iced ices idea idee ideo
ides ieee isis oafs obis oboe odds odes odic offs sacs safe said sass
scab scad seas secs seed sees sibs sics side sobs soda sods sofa

**Comment by zathras** [comment]
https://github.com/zathras/jrpn/commit/e35fea28ad2c1faf719689ce1c346ebc89c7e181

**Comment by ricknun** [comment]
The same problem image is still posted in the Microsoft Store.  (I don't know how to re-open a closed issue.)
![Capture](https://github.com/zathras/jrpn/assets/6921857/91e14ee5-d2b4-48a3-bd8f-f60a4dccbc7d)

**Comment by zathras** [comment]
Yeah, a bunch of other places besides - every platform has a different app store.  I'm not too worried about store listings showing an earlier version.
