### ISSUE TITLE
No key feedback 

### ISSUE THREAD

**Issue by carlo0501** [zathras/jrpn#101]
**JRPN 16C or 15C?**
JRPN 15C

There's no key feedback, irrespectively of the setting.
It's confirmed that key feedback click works on phone keyboard.
Phone is Samsung Note20 with Android 13 and OneUI 5.1.

**Comment by zathras** [comment]
Are you talking about haptic feedback, the click sound, or both?  What is your key feedback setting in the JRPN menu?

I see there's a known platform bug with Samsung phones.  See https://github.com/flutter/flutter/issues/73987 .  What happens when you try some of the setting changes described there?

**Comment by carlo0501** [comment]
I am referring to both, haptic and click.Luckily, when I activated "Touch interaction" on both System Audio and System Vibration settings both haptic and sound feedbacks got ok.So, this bug can be closed.Thanks  CarloInviato dal mio Galaxy
-------- Messaggio originale --------Da: Bill Foote ***@***.***> Data: 04/05/24  16:09  (GMT+01:00) A: zathras/jrpn ***@***.***> Cc: carlo0501 ***@***.***>, Author ***@***.***> Oggetto: Re: [zathras/jrpn] No key feedback  (Issue #101) 
Are you talking about haptic feedback, the click sound, or both?  What is your key feedback setting in the JRPN menu?
I see there's a known platform bug with Samsung phones.  See flutter/flutter#73987 .  What happens when you try some of the setting changes described there?

**Comment by zathras** [comment]
OK, thanks.  I created https://github.com/zathras/jrpn/issues/102 that I'll keep open; this might help other folks find the right settings.
