### ISSUE TITLE
15C STO/RCL of matrix values fails

### ISSUE THREAD

**Issue by ricknun** [zathras/jrpn#104]
**JRPN 16C or 15C?**
15C v2.1.14

**Describe the bug**
The attached program makes A = an nxn matrix with random contents.  With n = 2, 4 values will be put in the matrix in order a11 a12 a21 a22.  After execution a11 = the value that should have gone in a22 (wrong) and a12 = a21 = a22 = 0 (wrong).

**To Reproduce**
Load the program, turn on USER mode, 2 GSB 5 (run the program making A = a 2x2 matrix with random contents) RCL A (to recall A1,1 and see a value) RCL A (see 0, A1,2 is wrong) RCL A (see 0, A2,1 is wrong) RCL A (see 0, A2,2 is wrong).  Do the same but SST through the program keeping track of the 4 random values generated.  The A1,1 is the random number that should have gone in A2,2.

**Platform:**
Windows 10
[MatrixBug.txt](https://github.com/zathras/jrpn/files/15280897/MatrixBug.txt)

**Comment by zathras** [comment]
I think you're misunderstanding user mode.  The user mode setting is something that gets stored in a program -- setting user mode before running a program doesn't change a program that's already been stored.  The calculator indicates that an instruction is a user mode instruction by changing the dash to the "u" that's pictured in your image in #103.

This is how the real 15C behaves, too.

**Comment by ricknun** [comment]
Thanks for the explanation.  I returned my physical 15C Collector's Edition for a refund due to excessive key bounce.  So I no longer have a real calculator to compare to.

**Comment by ricknun** [comment]
Wait.  Am I confused or is there a problem with DSE?  I think the attached program should create matrix A with a11=4, a12=3, a21=2, a22=1.  Load it and GSB 5, then do RCL 0 (= 1, good) RCL 1 (=2, expected 1, an extra loop was done?!) 1 STO 1 (fix it) USER (turn on the mode), RCL A (a11 = 1, expected 4) RCL A (a12=3, correct) RCL A (a21=2, correct) RCL A (a22=1, correct).  Why are 5 loops happening?  I expect 4.
[MatrixBug2.txt](https://github.com/zathras/jrpn/files/15281379/MatrixBug2.txt)

**Comment by ricknun** [comment]
Never mind.  I found in the 15C manual "... when the last element is accessed by the “User” STO or RCL instruction - when R0 and R1 are returned to 1 - **program execution skips the next line**."  That is what happens in MatrixBug2 and is what I didn't understand.  Sorry for the interruption.
