### ISSUE TITLE
Unable to lock landscape mode in Android

### ISSUE THREAD

**Issue by johanw666** [zathras/jrpn#11]
The current version can not be locked to landscape mode like the Legacy version. Because I never have auto rotate on because it is impractical for me this means I can't use it in landscape mode on my phone. Until this is fixed I remain using the Legacy 1.1.4 version.

**Comment by zathras** [comment]
Note to self:  JRPN Legacy has Menu -> Configure -> Orientation, a dropdown that has auto/landscape/portrait.  Seems sensible.

**Comment by zathras** [comment]
Addressed by https://github.com/zathras/jrpn/commit/244f0b34d11ccb3ab3e0ba8f3bee391fcc47b85d
Will be in next release, which should hit the play store within a week or so.

**Comment by zathras** [comment]
Enhancement published in https://github.com/zathras/jrpn/releases/tag/2.0.1
