### ISSUE TITLE
Implement Romberg integration

### ISSUE THREAD

**Issue by jneb** [zathras/jrpn#114]
The integration routine in jrpn15c uses a Simpson based method. This means that the function to be integrated is evaluated at the endpoints.
The HP15C does not evaluate its endpoints and in the advanced functions handbook it is shown why this is useful for certain integrals.
Furthermore, the original method used by the HP15C is superior in precision.

Fortunately the proper method is already implemented for you in the hp42 simulator which can be found at 
https://github.com/thomasokken/free42/blob/master/common/core_math1.cc (the relevant formulas are in return_to_integ)

I dug up the description in the HP journal article on the HP34C and I think this is the real thing.

**Comment by zathras** [comment]
> The integration routine in jrpn15c uses a Simpson based method. This means that the function to be integrated is evaluated at the endpoints.

Close, but not quite.  Take a closer look at the code (`qromb`), and see also https://github.com/zathras/jrpn/issues/36

> <...> the original method used by the HP15C is superior in precision.

What are you basing this on?

I don't pretend deep expertise in numerical integration methods, but it seems like a statement that says method X is superior to method Y, in all cases, and for all time, without reservation is....  dubious.  Generally these things have tradeoffs.

> 
> Fortunately the proper method is already implemented for you in the hp42 simulator which can be found at https://github.com/thomasokken/free42/blob/master/common/core_math1.cc (the relevant tornadoes are in return_to_integ)
> 
> I dig up the description in the HP journal article on the HP34C and I think this is the real thing.

"Proper?"  I guess you mean "more faithful to the original."  I guess that might be true, and thanks for the link.  It's a big exaggeration to say it's implemented "for me," but it could serve as a model.

This might be worth considering, at some point.

**Comment by jneb** [comment]
I stand corrected.
I see both methods (let's call them jrpl and hp) are romberg methods.
The differences are: 
- hp uses midpoint (avoiding the interval endpoints), while jrpl uses trapezium
- hp does a substitution to sample more near endpoints, where jrpl does regular sampling

**Comment by zathras** [comment]
Porting the C++ algorithm from Free42 feels like scope creep.  I sent a message to its author for comments, but haven't heard back; I'm not sure what his source(s) were, either.  It's not clear to me that the Free42 algorithm is cleanroom, or that it's better and/or more faithful to the original 15C.

JRPN is a clean-room simulator; as such, it's not expected that functions like SOLVE will give *identical* results.  It's not an emulator.

If you know of a reasonable function where the simulator gives a bad result and the real calculator gives a good result, that would be interesting to know.  Based on the current state of things, I think I'll leave things as they are (with the improvements from #108).
