### ISSUE TITLE
15C / Chrome Browser only:  ISG gives incorrect results

### ISSUE THREAD

**Issue by zathras** [zathras/jrpn#119]
This is interesting!  A bug that shows up with ISG, only on the web version.  The bug is present in Crhome, but not Firefox (both running on Mac).  It shows up in both debug and deployed versions.

From e-mail:

While trying to run a program that uses ISG, I stumbled upon another problem:

I used register "I" but it doesn't appear to matter which register to use.

9.014
STO I
ISG I
RCL I

The expected result is 10.014.
However what I get is 108.01399.
...
I'm using https://jrpn.jovial.com/run15/index.html in a Chrome browser on a MacBook Pro (M2).

**Comment by pane** [comment]
The same in Chrome on Win 10 PC.
P

**Comment by zathras** [comment]
I'm not quite sure if the bug is mine, Dart's or Chrome's, but it's easy enough to fix.  As a "shortcut", I was converting a JRPN `Value` to an `int` by going through a `double`.  As a result, converting, say, 1.0 to 1 ended up being calculated as `(1e9 * pow(10, -9)).truncate()`.  On the native platform, the floating point implementation is stable enough that this always works, but that might not be guaranteed by the Dart spec.

The fix is easy enough:  Write a proper function to convert a `Value` to an `int`.

I verified the stable behavior for the native platform with the following program.  The comparison never fails on the native platform (running on Mac, but I doubt that makes a difference).  Running on Chrome, it fails reasonably frequently.

```
import 'dart:math';


main() {
  final rand = Random();
  for (int trial = 0; trial < 100000000; trial++) {
    final digits = rand.nextInt(10) + 1;
    final sb = StringBuffer(); 
    int result = 0;
    for (int i = 0; i < digits; i++) {
      result *= 10;
      final d = rand.nextInt(10);
      result += d;
      sb.write('$d');
    }
    for (int i = digits; i < 10; i++) {
      sb.write('0');
    }
    final resultD = double.parse(sb.toString()) * pow(10, digits - 10);
    if (resultD.truncate() != result) {
      print('$result $resultD');
    }
  }
}
```
