### ISSUE TITLE
Stuck on OFF

### ISSUE THREAD

**Issue by AllB556** [zathras/jrpn#120]
**15c**

Pressing ON shows OFF? on screen and I can't get out of it even by restarting. What to do?

**Debug Log**
If possible, a debug log would be great!  In JRPN, go to Menu -> Settings -> Capture Debug Log.  Then, operate the calculator to reproduce the problem.  Next, go to Menu -> Copy to Clipboard.  Then just paste your clipboard into the bug report.  Be sure to turn off debug logging in your settings when you're done!

The debug log captures calculator keystrokes, which gives me a nice, automated way of seeing exactly what's going on.  If you forget to turn of debug logging, nothing much bad happens -- every 1000 keystrokes, it resets the log, so it won't fill up memory.  But, all that extra stuff does take up some space, so you'll normally want it turned off.

**To Reproduce**
Tell me a bit about how to reproduce the problem.  This is especially important if you don't have a debug log!

**Expected behavior**

**Platform:**
 If relevant, some details on the platform are sometimes helpful.
- OS: [e.g. Linux, MacOS, Android, iOS]
 - Browser, if applicable
 - Any relevant version information

**Additional context**

**Comment by zathras** [comment]
You'll need to provide a lot more information.  See all that boilerplate text you left in?  You're supposed to answer the questions and edit as appropriate, not just leave the text there.

You'll need to reasonably describe your issue if you want help.

**Comment by AllB556** [comment]
> **15c**
> 
> Pressing ON shows OFF? on screen and I can't get out of it even by restarting. What to do?
> 
> **Debug Log** If possible, a debug log would be great! In JRPN, go to Menu -> Settings -> Capture Debug Log. Then, operate the calculator to reproduce the problem. Next, go to Menu -> Copy to Clipboard. Then just paste your clipboard into the bug report. Be sure to turn off debug logging in your settings when you're done!
> 
> The debug log captures calculator keystrokes, which gives me a nice, automated way of seeing exactly what's going on. If you forget to turn of debug logging, nothing much bad happens -- every 1000 keystrokes, it resets the log, so it won't fill up memory. But, all that extra stuff does take up some space, so you'll normally want it turned off.
> 
> **To Reproduce** Tell me a bit about how to reproduce the problem. This is especially important if you don't have a debug log!
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Platform:** If relevant, some details on the platform are sometimes helpful.
> 
> * OS: [e.g. Linux, MacOS, Android, iOS]
> * Browser, if applicable
> * Any relevant version information
> 
> **Additional context** Add any other context about the problem here.

That's about it. Android phone. Stuck showing OFF?  and I can't go on or back

> **15c**
> 
> Pressing ON shows OFF? on screen and I can't get out of it even by restarting. What to do?
> 
> **Debug Log** If possible, a debug log would be great! In JRPN, go to Menu -> Settings -> Capture Debug Log. Then, operate the calculator to reproduce the problem. Next, go to Menu -> Copy to Clipboard. Then just paste your clipboard into the bug report. Be sure to turn off debug logging in your settings when you're done!
> 
> The debug log captures calculator keystrokes, which gives me a nice, automated way of seeing exactly what's going on. If you forget to turn of debug logging, nothing much bad happens -- every 1000 keystrokes, it resets the log, so it won't fill up memory. But, all that extra stuff does take up some space, so you'll normally want it turned off.
> 
> **To Reproduce** Tell me a bit about how to reproduce the problem. This is especially important if you don't have a debug log!
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Platform:** If relevant, some details on the platform are sometimes helpful.
> 
> * OS: [e.g. Linux, MacOS, Android, iOS]
> * Browser, if applicable
> * Any relevant version information
> 
> **Additional context** Add any other context about the problem here.

**Comment by zathras** [comment]
OK, now you've told me what platform this is.  Good!  That's progress.  You've answered one of the two main questions that you've copy-pasted back to me.

Now, can you tell me how to reproduce the problem?  What did you do leading up to it getting stuck?

What do you mean by "stuck?"  When you press the OFF button again, what happens?  When you try getting into the menu, what happens?  Can you reset the calculator from the menu?  When you do, what happens?

This is covered under "To Reproduce:  Tell me a bit about how to reproduce the problem."

**Comment by AllB556** [comment]
Ah, Bill, these simple but not fully documented problems must be sent to try you. Thanks for your patience and help.When all else fails, sleep on it. So I did and the problem had disappeared in the morning.What happened was this: I'd just signed up for the HP 15c emulator and was checking it out. With increasing delight. And then I pressed the "ON" button, which on my actual physical 15c would turn it off. At that point everything stopped. Even pressing the "ON" button again wouldn't shift it. I got out of the app, and then reopened it. No luck - still no key seemed to shift it.So all's well. But I'll not try pressing "ON" again.Once again, many thanks for your help and forebearance. It's many years since I first started wrestling with computers, splicing together broken punched paper tape with a Ferranti Pegasus (with 11 bits of RAM) in 1958, when I was an aircraft engineer. Best wishesDavid ElmsSent from Android deviceOn 29/08/2024 02:15, Bill Foote ***@***.***> wrote:
OK, now you've told me what platform this is.  Good!  That's progress.  You've answered one of the two main questions that you've copy-pasted back to me.
Now, can you tell me how to reproduce the problem?  What did you do leading up to it getting stuck?
What do you mean by "stuck?"  When you press the OFF button again, what happens?  When you try getting into the menu, what happens?  Can you reset the calculator from the menu?  When you do, what happens?
This is covered under "To Reproduce:  Tell me a bit about how to reproduce the problem."

**Comment by zathras** [comment]
OK.  But...  Are you really sure it was "stuck"?

The behavior of the ON button is described in the user guide, over at https://jrpn.jovial.com/help.html, near the top.  So when you press ON, you should see yellow labels for the special ON-plus-key functions (self test, swap comma and decimal, etc.)  Pressing ON a second time should quit out of the app on Android.  (It behaves differently on iOS because Apple doesn't allow applications to terminate themselves.)

So if you press ON, and then ON again, and it doesn't quit, then that's a bug, but not one that I've ever seen before on an Android phone.  So are you sure that pressing ON a second time didn't quit the app?  What kind of phone do you have?  And, to be sure, you're running the Android app from the Google App store, and not just going to the website in your phone's browser, right?

You can always quit a non-responsive Android app from Android's app manager (under settings).  And there's the nuclear option of rebooting the phone :-)

What you should see when the calculator is running normally is: 
   press ON:  Label on ON key changes to yellow OFF
   press that key again:  Application quits

Also, if the calculator is  running normally, and you press ON (changing the label to OFF), and then press any key that doesn't have a yellow label, it should go back to the normal state.

At all times, the menu should work (the three dots in the upper-right hand corner).

**Comment by zathras** [comment]
BTW, speaking of paper tape, here's where my mother was working as a programmer from 1954 to 1956: 
 http://www.ddp116.org/products/math/math.pdf  By 1959, both my parents were programming at SDC, where they met, perhaps over the JOVIAL language.  I have a writeup about them at https://jovial.com/ .

**Comment by zathras** [comment]
Seems to be resolved.  Probably just pilot error?

**Comment by AllB556** [comment]
Hi BillSorry for slow response - was felled by a personal and physical bug.No, the issue is not resolved. Still on the 15c emulator pressing ON stops everything, with the key changing colour and showing OFF and the screen showing OFF ?Except the question mark is missing its dot.You showed me how to get out of it though, which is to go through the 3 dots to File > Reset. This clears everything. So it's no longer a problem this end. I'm telling you about it FYI though. And the phone's Android, and an Oppo A78.So, thanks for your help. Appreciated.Best wishesDavidPS The app is a delight to use. I'd recommend it to anyone.Sent from Android deviceOn 3/09/2024 05:47, Bill Foote ***@***.***> wrote:
Seems to be resolved.  Probably just pilot error?

**Comment by zathras** [comment]
OK, but when it's showing "OFF?" in the LCD display, what happens when you press one of the calculator keys?

**Comment by AllB556** [comment]
This is incredible. Everything works fine now. Either you've done something, or this morning's OS upgrade did something, or the Computer Gods are feeling friendly.Either way, many thanks, Bill.Sent from Android deviceOn 4/09/2024 07:17, Bill Foote ***@***.***> wrote:
OK, but when it's showing "OFF?" in the LCD display, what happens when you press one of the calculator keys?
