### ISSUE TITLE
CHS not behaving correctly in Unsigned mode

### ISSUE THREAD

**Issue by meltdown03** [zathras/jrpn#121]
**JRPN 16C or 15C?**
16C

**Describe the bug**
CHS not changing anything when in unsigned mode (DEC,HEX,BIN,OCT)
Also, when 0 is in X and CHS is pressed, the G annunciator is displayed when it shouldn't be.

**To Reproduce**

1st example:

DEC
f -> UNSIGN
1
CHS     ---      display remains at "1"

2nd example:

DEC
16 f -> WSIZE
f -> UNSIGN
60000
CHS     ---      display remains at "60000"

**Expected behavior**
1: Display should show max value for current wordsize in whatever mode it's in. (G set)
2: Display should change to 5536 with G set

**Platform:**
 If relevant, some details on the platform are sometimes helpful.
Linux

**Additional context**
When 0 is used on the example above, the G annunciator is displayed, but on the real hardware, the display just shows at 0, not changing the G

**Comment by zathras** [comment]
Ah, thanks.  Yes, it looks like this is specified behavior.  Page 30 of the users guide says "Changing signs in Unsigned mode has no meaning," but it goes on to specify the meaning of the CHS key in unsigned mode.  Ha!  It indeed specifies that it gives the 2's complement of the number, and sets overflow.

**Comment by zathras** [comment]
Note to self:  The behavior of clearing the G flag is specified on page 40 of the user's guide.  CHS clears the G flag in integer mode, but not in floating point mode.

**Comment by zathras** [comment]
Published in 2.1.16
