### ISSUE TITLE
Determinant calculation

### ISSUE THREAD

**Issue by jneb** [zathras/jrpn#123]
**JRPN 15C**

**Determinant gives wrong answer**

**Debug Log with zeros removed**
{"version":1,"modelName":"15C","settings":{"menuEnabled":false,"windowEnabled":false,"longNumbers":1,"euroComma":true,"showAccelerators":true,"systemOverlaysDisabled":false,"orientation":0,"keyFeedback":5,"msPerInstruction":0.0},"trigMode":"RAD","displayMode":"x4","integerSignMode":"2","wordSize":56,"stack":["91234543210006","1000000000000","1111100000004","1234543210008"],"lastX":"a111eeeeeee000","flags":[false,false,false,false,false,false,false,false,false,false],"memory":{"storage":"20140e0b01ed0a61761d67ff9876fe44b61001867801861978b710610186761c7901ed938602ed92e7077d0bfe3a0d020d1914761bdafeeadbdd511950fe06dd19dced7628a6fe0129b6b78e7c8d4efee6397600000...000000000000000000000000000000000000000000001234567654012011111100000060152415729202401234568765012020000000000000100000000000001000000000000","program":{"lines":76,"currentLine":56,"returnStack":[3,35,3735928559,0,0,0,0],"returnStackPos":0},"I":"a111eeeeeee001"},"debugLog":{"initialState":{"version":1,"modelName":"15C","settings":{"menuEnabled":false,"windowEnabled":false,"longNumbers":1,"euroComma":true,"showAccelerators":true,"systemOverlaysDisabled":false,"orientation":0,"keyFeedback":5,"msPerInstruction":0.0},"trigMode":"RAD","displayMode":"x4","integerSignMode":"2","wordSize":56,"stack":["0","1000000000000","4000000000000","1600000000001"],"lastX":"a111eeeeeee000","flags":[false,false,false,false,false,false,false,false,false,false],"memory":{"storage":"20140e0b01ed0a61761d67ff9876fe44b61001867801861978b710610186761c7901ed938602ed92e7077d0bfe3a0d020d1914761bdafeeadbdd511950fe06dd19dced7628a6fe0129b6b78e7c8d4efee6397600000 ... 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001234567654012011111100000060152415729202401234568765012020000000000000100000000000001000000000000","program":{"lines":76,"currentLine":56,"returnStack":[3,35,3735928559,0,0,0,0],"returnStackPos":0},"I":"a111eeeeeee001"},"numRegisters":31,"resultMatrix":2,"matrices":[{"columns":2,"values":["1600000000001","4000000000000","4000000000000","1000000000000"],"rowSwaps":null},{"columns":1,"values":["91000000000000","1111111110008"],"rowSwaps":null},{"columns":2,"values":["1600000000001","4000000000000","2500000000999","0"],"rowSwaps":[0,1]},{"columns":2,"values":["1234567901018","1111111111009","1111111111009","1000000000000"],"rowSwaps":null},{"columns":2,"values":["1234567901018","1111111111009","9000000001990","91000000000008"],"rowSwaps":[0,1]}],"lastRandom":0.45472346512203354},"keys":[1,1,1,1,1,-1,0,1,2,125,-1,59,102,1,1,1,1,1,-2,11,146,102,-2,127,146,102,146,102,1,146,102,182,20,102,-1,0,9]},"endDisplay":"-1,234,543.210","numRegisters":31,"resultMatrix":2,"matrices":[{"columns":2,"values":["1234543210008","1111100000004","1111100000004","1000000000000"],"rowSwaps":null},{"columns":1,"values":["91000000000000","1111111110008"],"rowSwaps":null},{"columns":2,"values":["1234543210008","1111100000004","9000090001995","91000000000998"],"rowSwaps":[0,1]},{"columns":2,"values":["1234567901018","1111111111009","1111111111009","1000000000000"],"rowSwaps":null},{"columns":2,"values":["1234567901018","1111111111009","9000000001990","91000000000008"],"rowSwaps":[0,1]}],"lastRandom":0.45472346512203354}

**To Reproduce**
Type
2 DIM A
RESULT C
MATRIX 1
USER on
11111 x² STO A
LASTx STO A STO A
1 STO A
RCL MATRIX A
MATRIX 9
this gives -123454321

**Expected behavior**
(close to) zero 

**Platform:**
- Android 14

**Additional context**
If you replace 11111 by a smaller number, e.g. 4, the result is correct

**Comment by zathras** [comment]
Not a bug:  Upon analysis, this is due to different rounding behavior.  I note that on the real 15C, matrix C differs from the simulator.  On the real 15C, Matrix C holds [[123,454,321.0, 11111], [9.0001e-5, -1.1000e-11]].  In the simulator, it's [[123,414,321.0, 11111], [9.0001e-5, -1,9999e-2]].

As per the README,. the simulator does not try to exactly duplicate the algorithms used in the original.  For that, a hardware emulator with the original firmware is what you really want.  Different results at the limit of the calculator's precision are to be expected.

That said, I'll take a look at the LU decomposition to see if there's a  reasonable way to align the behavior at this edge case a bit more with the original.

**Comment by zathras** [comment]
From experimentation, it looks like the real 15C uses 1e-10 as the minimum pivot value.  Plugging that in gets better results here, and with some singular matrices I tried.  It didn't break any of the existing regression tests, so a priori this should be OK.

@jneb, how much do you know about forming the LU decomposition of matrices that are nearly singular?  I'd be interested in a review of the new code, in the upcoming putback...

**Comment by jneb** [comment]
I find it surprising that the error is so big.
There's probably some subtlety in the way the 15C algorithms suppress
rounding errors to prevent this from happening.

Op wo 25 sep 2024 19:08 schreef Bill Foote ***@***.***>:

**Comment by zathras** [comment]
> I find it surprising that the error is so big.

@jneb See the subsequent comment, especially my question about LU decomposition.  See also https://github.com/zathras/jrpn/commit/9bbe0ecaa1cb4297e1067191a52ccf46606f353d

**Comment by zathras** [comment]
Published in 2.1.16
