### ISSUE TITLE
Key press feedback 

### ISSUE THREAD

**Issue by FredMc55** [zathras/jrpn#20]
Might be nice to have some tactical feedback on a key press. User choice of click, buzz, both, or none.

**Comment by zathras** [comment]
Good idea.

**Comment by zathras** [comment]
NOTE:  I just used the standard Flutter Feedback.forTap(context).  On Android, it make a click sound (if you have that turned on in your phone, which I don't usually :-) ).  On MacOS, it does nothing.

Just going with the standard Flutter mechanism seems like the right thing to do here.

It might take some time until this makes it to the Google app store.  The streets are sort of torn up right now, doing the 15C simulator, and it looks like Flutter has changed enough so I have to re-create the Android project.

**Comment by zathras** [comment]
Published:  2.1.2
