### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by johanw666** [zathras/jrpn#35]
Sorry to open this via an issue, but I failed to compile jrpn via Android Studio.

I installed flutter, Visual Studio and flutter doctor only reported that I don't have Chrome installed but that should not be a problem AFAIK.

Android Studio reported:
```
C:\S\jrpn-2.1.3\jrpn\jrpn15\.dart_tool\package_config.json does not exist.
Did you run this command from the same directory as your pubspec.yaml file?
Target gen_dart_plugin_registrant failed: Exception: 
```
Should I do something with Dart first?

**Comment by zathras** [comment]
"flutter pub get," probably.

**Comment by johanw666** [comment]
That command shows that everything is OK but I still get the same build error.

**Comment by zathras** [comment]
If you want help with how to compile flutter apps, try at least providing something more complete, like a capture of the console output starting with "flutter doctor" and "flutter clean."

**Comment by johanw666** [comment]
I did a flutter clean, then it told me to upgrade so flutter upgrade, then flutter pub get in both the jrpn15 and its parent directory. Now it builds. Thanks for the help.
