### ISSUE TITLE
Orientation setting is not stored

### ISSUE THREAD

**Issue by johanw666** [zathras/jrpn#37]
**JRPN 16C or 15C?**
Both 15C and 16C

**Describe the bug**
When I select "Landscape", the calculator switches to landscape view, but when I close the calculator and re-open it the setting is back to "system".

**Platform:**
 If relevant, some details on the platform are sometimes helpful.
- OS: Android 11, Samsung A50

**Comment by zathras** [comment]
Are you saving the calculator state, either with File -> Save, or by turning the calculator off with the on/off button?

**Comment by johanw666** [comment]
Saving works, but that is not the behaviour that one expects from an Android app.

**Comment by zathras** [comment]
Issue captured in #38
