### ISSUE TITLE
Autosave state when settings changed

### ISSUE THREAD

**Issue by zathras** [zathras/jrpn#38]
JRPN intentionally only saves state when explicitly asked to, but it would avoid confusion if changing a setting on the calculator were considered an explicit ask.

Surprisingly, Flutter doesn't have a way of getting notified when an app is closed (through the window manager on Desktop, or by Android deciding it wants to).  That's why the decision was made to only save state when explicitly requested.  Ref:  https://stackoverflow.com/questions/62059364/is-there-anyway-to-detect-app-closed-on-flutter .  I double-checked this, and from memory, a closing application isn't even given an `AppLifecycleState.paused` first.

**Comment by johanw666** [comment]
> Surprisingly, Flutter doesn't have a way of getting notified when an app is closed

Isn't there an onChange event handler when the setting changes? That seems a more logical place to save it than an app close.
