### ISSUE TITLE
applicationId changed?

### ISSUE THREAD

**Issue by IzzySoft** [zathras/jrpn#40]
I just wonder that the APK at the latest release has a different `applicationId` than the previous one from 8/2021 – and what the implications are, as different `applicationId` means different app, so this is no update to the last one but a different app:

* the two are indeed different apps (so how to tell them apart by release file names or tags? The APK at tag 2.0.1 is named `
android_universal.apk` and identifies as `com.jovial.jrpn2`. The one at tag 2.1.3 is indeed named `jrpn15_android_app-release.apk` and identifies as `com.jovial.jrpn15`. So what file name to look out for if one wants to update `com.jovial.jrpn2` (think of an automated updater, as this is about [your app in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.jovial.jrpn2)
* the two should be the same, and renaming was accidental (because, where was the previous 15?)
* Maybe the two variants could be combined into a single APK to avoid the confusion?

**Comment by zathras** [comment]
There are two different applications built from the same source base -- see https://jrpn.jovial.com/ .  Making that work across various build environments took some reorganization.

For an automated build, I'd recommend using https://github.com/zathras/jrpn15_build and/or https://github.com/zathras/jrpn16_build, as appropriate.  I added some notes to the main JRPN README about the build structure.

**Comment by IzzySoft** [comment]
Apologies if my phrasing wasn't clear. I wasn't asking about the build process, but about fetching the corresponding APKs. My repo is just a "simple binary repo", I do not build the apps myself but rather fetch the APKs built by the corresponding developers. So what I'd need is a clear naming pattern to make sure I fetch only the matching APKs (btw, the two repositories you referred to do not provide any APKs at their releases).

The one currently listed with my repo is, as outlined above, `com.jovial.jrpn2`. So how do I make sure only to fetch APKs with that `applicationId`? I can exclude or restrict-to by using regular expressions on the file and/or tag names. So I could e.g. `ApkIgnore: /jprn15/i` to not fetch that one, or `/jprn1[56]/i` to exclude 16 as well. But would that ensure I fetch all jprn2 builds? What would you suggest?

**Comment by zathras** [comment]
OK.  The original app, JPRN 16, aka com.jovial.jrpn2, is called `jrpn16_android_app-release.apk`.  The newer, second app, JRPN 15, aka com.jovial.jrpn15, is called `jrpn15_android_app-release.apk`.  The original one is a programmer's calculator; the newer one is a scientific calculator.  It's possible for there to be a release with just one of them, or with both.

**Comment by IzzySoft** [comment]
Thanks a lot! Added the 15C to my repo then as well, matching the corresponding APK files as you indicated. While on it, I also updated the license (you originally used MIT, I've now set it to GPL3+ as your repo here shows).
