### ISSUE TITLE
[Android] Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [zathras/jrpn#41]
Please support the Android 13 "Themed App Icons" feature.

![Screenshot_2023-04-03-04-16-25-845_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/229388884-83f60ad1-d48c-4559-a24a-6027db56fb0e.jpg)

**Comment by zathras** [comment]
Hi Mohammed / @xmha97 ,

Do you know how to directly install an APK?  If so, could you try this one, and let me know how it looks on your launch screen?  Google's documentation around adaptive icons is rather weak...  I _think_ you'll get a purple circle with a white picture of Jupiter, a horizontal line, and the text "15C" at the bottom, but given how vague and disconnected their documentation is, I'm not sure that's what you'll get.

[jrpn15_android_app-release.apk.zip](https://github.com/zathras/jrpn/files/11153728/jrpn15_android_app-release.apk.zip)

Thanks,

Bill

**Comment by xmha97** [comment]
I can now confirm that the app icon is now adaptive.
But the app still does not have a monochrome icon.
Since I'm not an Android developer and also the Google docs are weak, I can't help with this issue, but anyway, please don't close this issue.
(Sorry for my bad English)

![Screenshot_2023-04-05-06-17-02-620_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/229968928-f13bc49f-c33b-4e3a-a6ab-6872d4f9dcfc.jpg)

**Comment by zathras** [comment]
Hmmm...  OK.  I did a little more digging, and the Flutter tool for app icons doesn't support Google's monochrome icon attribute (viz https://stackoverflow.com/questions/71109063/how-to-implement-a-themed-monochrome-icon-for-material-you).  It _might_ work if I just manually edit it in, so I'll give that a shot.

https://developer.android.com/develop/ui/views/launch/icon_design_adaptive talks about monochrome icons, but it doesn't say what colors I'm supposed to use for the foreground or background.  White and black?  Black and white?  Black and transparent?  Beats me!

So, I'll start with a guess.  This image has a monochrome element added into the manifest, with a transparent background and a black foreground.  Maybe it'll work?  If not, by looking at the result I can probably figure out what it wants me to do.  Let me know what this one looks like.
[jrpn15_android_app-release.apk.zip](https://github.com/zathras/jrpn/files/11154880/jrpn15_android_app-release.apk.zip)

Thanks,

Bill

**Comment by xmha97** [comment]
This version is good 👍

![Screenshot_2023-04-05-09-15-48-286_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/229992237-d51bc818-94f6-4b99-a8d9-b41a7b522a19.jpg)

![ResizedImage20230405_091753.png](https://user-images.githubusercontent.com/23485114/229992239-95739ea6-e59d-44ae-908f-60b31e0ff43d.png)

![Screenshot_2023-04-05-09-15-56-710_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/229992238-623151aa-9760-4e68-8cf9-a7ca7e1f72d6.jpg)



You can close this issue.
Thanks 🙏

**Comment by zathras** [comment]
Great!  Thanks for letting me know about this, and for testing the trial builds.

I should be updating this on Google's app store within a week or two.  You might want to reinstall the app store version when that happens, so you get any subsequent bugfixes.  I'll close the issue when I do that.

**Comment by zathras** [comment]
Enhancement request in `flutter_launcher_icons`:  https://github.com/fluttercommunity/flutter_launcher_icons/issues/419
