### ISSUE TITLE
[build] Questions about building on Linux (not snap)

### ISSUE THREAD

**Issue by braoult** [zathras/jrpn#44]
OS: Xubuntu 23.04
project: jrpn15
Trying to build a "linux" target (without root) with the command `flutter build linux --release`, I get the following error (normal):
```
CMake Error at cmake_install.cmake:66 (file):
  file INSTALL cannot copy file
  "/home/br/dev/jrpn/jrpn15/build/linux/x64/release/intermediates_do_not_run/jrpn15"
  to "/usr/local/jrpn15": Permission denied.
```
Obviously, I don't have the rights on `/usr/local`. As running `sudo flutter build linux --release` gives many warnings about the danger to run flutter as root, what is the correct way to do the installation ?

Something else puzzles me: In the error message above, the binary destination file seems to be `/usr/local/jrpn15`. Should not it be installed in `/usr/local/bin/` ?

**Comment by zathras** [comment]
I very much doubt that's anything to do with JRPN.  The project config doesn't mention anything about those paths; normally "flutter build" just builds in a local sub-directory.  Maybe it's something to do with your installation/config?  Have your tried e.g. creating a trivial flutter project yourself, to see if there's a error?

In any case, diagnosing your flutter installation isn't really in scope here.
