### ISSUE TITLE
`f` Clear `REG` does not clear registers

### ISSUE THREAD

**Issue by babetoduarte** [zathras/jrpn#54]
**JRPN 16C or 15C?**

JRPN 15C

**Describe the bug**

When the F key is pressed and then the Clear REG key is pressed, the registers are not cleared. This is apparently mapped to the `f` Clear `SUM` sequence instead. 

**Debug Log**
{"version":1,"modelName":"15C","settings":{"menuEnabled":true,"windowEnabled":true,"euroComma":false,"showAccelerators":false,"systemOverlaysDisabled":false,"orientation":0,"keyFeedback":0},"displayMode":"x4","integerSignMode":"2","wordSize":56,"stack":["4000000000000","4000000000000","3000000000000","2000000000000"],"lastX":"0","flags":[false,false,false,false,false,false,false,false,false,false],"memory":{"storage":"000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","program":{"lines":0,"currentLine":0,"returnStack":[0,0,0,0,0,0,0],"returnStackPos":-1},"I":"0"},"debugLog":{"initialState":{"version":1,"modelName":"15C","settings":{"menuEnabled":true,"windowEnabled":true,"euroComma":false,"showAccelerators":false,"systemOverlaysDisabled":false,"orientation":0,"keyFeedback":0},"displayMode":"x4","integerSignMode":"2","wordSize":56,"stack":["0","0","0","0"],"lastX":"0","flags":[false,false,false,false,false,false,false,false,false,false],"memory":{"storage":"000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","program":{"lines":0,"currentLine":0,"returnStack":[0,0,0,0,0,0,0],"returnStackPos":-1},"I":"0"},"numRegisters":20,"resultMatrix":0,"matrices":[{"columns":0,"values":[],"rowSwaps":null},{"columns":0,"values":[],"rowSwaps":null},{"columns":0,"values":[],"rowSwaps":null},{"columns":0,"values":[],"rowSwaps":null},{"columns":0,"values":[],"rowSwaps":null}],"lastRandom":0.23225264202069384},"keys":[1,125,2,125,3,125,4,125,-1,122,-3,-1]},"endDisplay":" 4.0000     ","numRegisters":20,"resultMatrix":0,"matrices":[{"columns":0,"values":[],"rowSwaps":null},{"columns":0,"values":[],"rowSwaps":null},{"columns":0,"values":[],"rowSwaps":null},{"columns":0,"values":[],"rowSwaps":null},{"columns":0,"values":[],"rowSwaps":null}],"lastRandom":0.23225264202069384}

**To Reproduce**
Fill up the registers, then press f+Clear REG, and the screen will still display the current value, and if you explore the internals, all registers are holding values.

The desired functionality is mapped to f+Clear Sum. 

**Expected behavior**
All the registers should be cleared, and equal to 0.0000

**Platform:**
 Google Pixel 6a, Android 13. Downloaded JRPN 15C from the Play Store. 

**Additional context**
Just wanted to say thank you for producing and maintaining these awesome apps!

**Comment by babetoduarte** [comment]
I'm terribly sorry, I realized after re-reading the 15C's manual that  f+Clear REG does NOT affect the stack, nor the last X registers. My bad! Please delete and disregard this issue.

**Comment by zathras** [comment]
Thanks for catching this!

**Comment by zathras** [comment]
Oh, interesting.  I've never used a 12C, but my 15C came in really handy taking calculus at UCLA in '83 :-)
