### ISSUE TITLE
No release 2.1.8 yet

### ISSUE THREAD

**Issue by johanw666** [zathras/jrpn#61]
There is no release of 2.1.8 yet, and Google Play offers only clumsy split apk's.

Please publish a release as before.

**Comment by zathras** [comment]
It's in progress.  It's not an entirely automatic process.  Notably, it involves me going into the office on Monday and doing a smoke test on the MacOS version, to make sure it got built correctly.

**Comment by johanw666** [comment]
OK, thanks. I'll wait then.
