### ISSUE TITLE
`FIX I`, `SCI I` and `ENG I` operate on the wrong register

### ISSUE THREAD

**Issue by eliasrg** [zathras/jrpn#65]
**JRPN 16C or 15C?**
15C

**Describe the bug**
`FIX I`, `SCI I` and `ENG I` should set the precision according to the contents of the index register, but seem to take input from the X register instead.

**Debug Log**
`{"version":1,"modelName":"15C","settings":{"menuEnabled":false,"windowEnabled":true,"longNumbers":0,"euroComma":false,"showAccelerators":false,"systemOverlaysDisabled":true,"orientation":0,"keyFeedback":3},"displayMode":"x0","integerSignMode":"2","wordSize":56,"stack":["0","0","0","0"],"lastX":"91000000000000","flags":[false,false,false,false,false,false,false,false,false,false],"memory":{"storage":"000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","program":{"lines":0,"currentLine":0,"returnStack":[4,3735928559,0,0,0,0,0],"returnStackPos":-1},"I":"5000000000000"},"debugLog":{"initialState":{"version":1,"modelName":"15C","settings":{"menuEnabled":false,"windowEnabled":true,"longNumbers":0,"euroComma":false,"showAccelerators":false,"systemOverlaysDisabled":true,"orientation":0,"keyFeedback":3},"displayMode":"x3","integerSignMode":"2","wordSize":56,"stack":["0","0","0","0"],"lastX":"91000000000000","flags":[false,false,false,false,false,false,false,false,false,false],"memory":{"storage":"000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","program":{"lines":0,"currentLine":0,"returnStack":[4,3735928559,0,0,0,0,0],"returnStackPos":-1},"I":"0"},"numRegisters":20,"resultMatrix":2,"matrices":[{"columns":0,"values":[],"rowSwaps":null},{"columns":0,"values":[],"rowSwaps":null},{"columns":0,"values":[],"rowSwaps":null},{"columns":0,"values":[],"rowSwaps":null},{"columns":0,"values":[],"rowSwaps":null}],"lastRandom":0.8889368443064132},"keys":[5,146,73,-5,-1,10,73]},"endDisplay":" 0.         ","numRegisters":20,"resultMatrix":2,"matrices":[{"columns":0,"values":[],"rowSwaps":null},{"columns":0,"values":[],"rowSwaps":null},{"columns":0,"values":[],"rowSwaps":null},{"columns":0,"values":[],"rowSwaps":null},{"columns":0,"values":[],"rowSwaps":null}],"lastRandom":0.8889368443064132}`

**To Reproduce**
Enter the keystrokes
    5
    STO I
    CLx
    FIX I
The display is set to 0 decimals.

**Expected behavior**
The display should be set to 5 decimals.

**Platform:**
Android, Play Store, version 2.1.8 (13 Oct 2023)

**Additional context**
See page 109 of the owner's handbook. Indirect flag control, also described there, seems to work fine. I haven't checked whether indirect branching suffers from the same problem.

**Comment by billf-pshs** [comment]
Thanks for catching this, and submitting the report!  The bug was quite localized to just FIX/ENG/SCI, so indirect branching is probably fine.  Let me know if you want a test build for Android.  Otherwise it might be a couple of weeks before I turn the crank on a full release for all platforms.

I printed out your theory of very nearly everything -- We'll have to see if a software engineer can answer physics questions like a proper physicist.  I'll have to get past trying to relate quarks to gold-pressed latinum first.

**Comment by zathras** [comment]
Released in 2.1.9
