### ISSUE TITLE
Insufficiently strict check of internal float format ("Error 6" on 16C)

### ISSUE THREAD

**Issue by meltdown03** [zathras/jrpn#68]
I noticed on my real 16C that if I store something other than a zero in **I**, then switch to Float mode, and try to recall it (or it's contents), I get an ERROR 6. (Page 57 of the manual shows that it's normal behavior.)  JRPN16 does not have this limitation.

Example:
`HEX`
`1, STO I`
`f, FLOAT .`
`RCL I` -> **Error 6**

It seems that it, when in Float mode, it stores the **I** in using the same big-endian BCD format as the other float values. EX:
`f, Float .`
`1,  STO I`
`HEX`
`RCL I` -> **1000000000000 h**

So, maybe it does the reverse of the conversion when switching _TO_ float mode which results in an unusable Index register number? I don't really understand the 68-bit part of it though, maybe that's used for non-floating point.

**Comment by zathras** [comment]
Ha!  That's a cool little bug.

"Help -> Show calculator internals" reveals what's going on.  It's just blindly copying the value 0x1 into X, even though that's an invalid float value (I think it's a mantissa of 0 with an exponent of 1, which isn't valid - 0 is represented as a mantissa of 0 and an exponent of 0).  The simulator just needs to check the value of I for validity when in float mode.  I might even just put the check for a valid float value at a deeper level, like the method that assigns a value to X.

**Comment by meltdown03** [comment]
I saw that in the internals. Too bad I cant see the real hardware ones. But, I just tried it in the HP16C emulator (Emulator based on a ROM??):
![image](https://github.com/zathras/jrpn/assets/6166536/23a77061-7e5a-45d3-989f-ac4f6c2bfd05)

![image](https://github.com/zathras/jrpn/assets/6166536/1af8f521-136a-4681-9cf7-ccc8ab25c8c0)

**Comment by zathras** [comment]
The check of the internal format was too forgiving with the exponent.  Fixing that exposed a couple of other issues; I'll need to audit places where I manipulate the internal format before I publish this.

**Comment by zathras** [comment]
A note on this...  I haven't forgotten.  I've been in the process of moving, after completing service with the Peace Corps.  It may be another few weeks before I get settled enough to really sit down and audit this properly.

**Comment by meltdown03** [comment]
No problem, I built it from source and am using it as is for now.
