### ISSUE TITLE
Small tweak: HEX "C" is lowercase, actual is uppercase

### ISSUE THREAD

**Issue by meltdown03** [zathras/jrpn#75]
**JRPN 16C or 15C?**

16C

**Describe the bug**
Hexadecimal `c` is lowercase, but only the `b` and `d` are lowercase on physical device as the manual states (pg. 28) to differentiate them from `8` and `0`.

**To Reproduce**
Press HEX,
Press C

**Expected behavior**
An uppercase `C` shown in the LCD display.

**Platform:**
Linux and Android

**Additional context**
I modified the `lcd_display.dart` file, line 355 locally and rebuilt:
`  'c'.codeUnitAt(0): Digit._p([_s.top, _s.lowL, _s.upL, _s.bot]),`

**Comment by zathras** [comment]
Ha!  Thanks for catching this.  After 35 years of seeing mostly lowercase hex, I just naturally went with "c", but casting myself back to the '80s, I would have used "C" back then, too.  I'll put the fix back after I finish dealing with https://github.com/zathras/jrpn/issues/73 .

**Comment by zathras** [comment]
Published in 2.1.12
