### ISSUE TITLE
(Cosmetic) Floating point number entry/grow LCD:  Limit number of digits

### ISSUE THREAD

**Issue by zathras** [zathras/jrpn#79]
When entering an FP number, it makes sense to relax the max digits constraint somewhat, e.g. so one can enter 1.234567891e-99, but having no limit allows silly results like this:
![Screenshot 2024-02-22 at 10 18 41 AM](https://github.com/zathras/jrpn/assets/20762139/170ef316-30fc-4c8e-8375-3ce219aacb64)

**Comment by zathras** [comment]
Come to think of it, I like it better where the limit stays the same in both cases (it never allows more than ten digits).  A typical user gesture for me on the physical calculator is to press 1.999999999999999, relying on the calculator to stop digit entry when I reach the tenth digit.  That doesn't work with the "improvement" of allowing longer entry, and rounding that to exactly 2 can be surprising.

**Comment by pane** [comment]
> Come to think of it, I like it better where the limit stays the same in both cases (it never allows more than ten digits). A typical user gesture for me on the physical calculator is to press 1.999999999999999, relying on the calculator to stop digit entry when I reach the tenth digit. That doesn't work with the "improvement" of allowing longer entry, and rounding that to exactly 2 can be surprising.

I praise this limitation of entry to nature of the number - I also bumped into some surprises on 15C before this enhancement (1.999999999 -> H.MS vs 1.99999999999 -> H.MS) - now it works more intuitively. I like 16C growing display very much (although I never had and tried 16C before this looks much more easier for long words). P

**Comment by zathras** [comment]
Published in 2.1.12
