### ISSUE TITLE
small enhancements

### ISSUE THREAD

**Issue by whuyse** [zathras/jrpn#82]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
15C version: 

- small 'c' should be uppercase 'C' everywhere
- in the printout, eg   042 {  44 15 u } u STO E should show as    042 {  u  44 15 } u STO E
- remove the 000 { } line
- include byte size in the heading
- an escape character to include comments in listings, if possible? --, @, (), whatever so that I can upload my commented code again.

**Describe any alternatives you've considered**
None. These are just suggestions.. I can and will live with JRPN as it is ;-)

**Additional context**

**Comment by zathras** [comment]
> * small 'c' should be uppercase 'C' everywhere
Where isn't it?
> * in the printout, eg   042 {  44 15 u } u STO E should show as    042 {  u  44 15 } u STO E

Do you know if this is what Torsten's 15C emulator does?  I can check, but if you know off hand, that would be helpful.

> * remove the 000 { } line

I don't really like the 000 line either, but I modeled the export format off of Torsten's, at his request, so that programs could easily be transferred between the two.  His simulator produces that line.  I'm not sure if it's necessary or not, but I wanted the two formats to be as close as possible.

> * include byte size in the heading

Do you mean number of lines?  The size of a program in bytes is something users don't usually see -- some instructions occupy two bytes.

> * an escape character to include comments in listings, if possible? --, @, (), whatever so that I can upload my commented code again.

Doesn't "#" work?

**Comment by whuyse** [comment]
> > * small 'c' should be uppercase 'C' everywhere
> >   Where isn't it?
? I could've sworn matrix C was in lowercase. I'm getting old.

> > * in the printout, eg   042 {  44 15 u } u STO E should show as    042 {  u  44 15 } u STO E
> 
> Do you know if this is what Torsten's 15C emulator does? I can check, but if you know off hand, that would be helpful.
No, because I can't install it.. but in the 15C (and your simulator as well) in PRGM mode, the 'u' is put before the numbers.

> 
> > * remove the 000 { } line
> 
> I don't really like the 000 line either, but I modeled the export format off of Torsten's, at his request, so that programs could easily be transferred between the two. His simulator produces that line. I'm not sure if it's necessary or not, but I wanted the two formats to be as close as possible.
No problem.. 

> 
> > * include byte size in the heading
> 
> Do you mean number of lines? The size of a program in bytes is something users don't usually see -- some instructions occupy two bytes.
Exactly. Number of lines is easy enough to see, but byte size would be handy if it were included..
> 
> > * an escape character to include comments in listings, if possible? --, @, (), whatever so that I can upload my commented code again.
> 
> Doesn't "#" work?
Don't know, and it is not in the help file.. I will try it out.

**Comment by zathras** [comment]
About "u" in the listings...  I checked,  and that is part of Torsten's syntax.  He has a bunch of sample programs at https://hp-15c.homepage.t-online.de/download.htm#ProgramExamples (which I copied over to the JRPN test suite, BTW).  There, you can find examples, like this line from "HP-15C Advanced Functions Handbook - Page 100.15c": 

   020 {    45 24  u } RCL (i)

I think Torsten might have gotten the syntax from somewhere else -- maybe the Swiss Micro 15C clones?  Anyway, this is an established part of the syntax; JRPN can't change it without breaking compatibility.

I guess giving the size occupied by program instructions might be interesting to some, and it's easy enough to add a comment to the listing.

**Comment by pane** [comment]
> > No, because I can't install it.

I am able to use Win app following this steps without need to install it:

> I see that a .msix file is just a zip file, with some extra stuff in it. So that means you can download a .msix, rename it something.zip, and unzip it. So, maybe try unzipping the msix somewhere, and running jrpn15c.exe? You might need to open a console window, make the current working directory be the one containing the .exe, and launch it from the command line.

**Comment by whuyse** [comment]
> > > No, because I can't install it.
> 
> I am able to use Win app following this steps without need to install it:
> 
> > I see that a .msix file is just a zip file, with some extra stuff in it. So that means you can download a .msix, rename it something.zip, and unzip it. So, maybe try unzipping the msix somewhere, and running jrpn15c.exe? You might need to open a console window, make the current working directory be the one containing the .exe, and launch it from the command line.

That used to work like 10 years ago but they have gotten smarter than that I'm afraid. .exe files can only be executed from C:\Program Files, and I don't have write access to that folder.

**Comment by meltdown03** [comment]
I have one request for the debug window (calculator internals), reverse the order of the stack so it's:
```
T:
Z:
Y:
X:
```
It's not a big deal but would match the manual a little better.

**Comment by zathras** [comment]
> I have one request for the debug window (calculator internals), reverse the order of the stack

Makes sense; done.

**Comment by zathras** [comment]
Published in 2.1.12
