### ISSUE TITLE
common pool behaviour incorrect when solving or integrating

### ISSUE THREAD

**Issue by boxercollie** [zathras/jrpn#86]
JPRN 15C

On the original, the integration function uses 23 registers from the common pool. That means if fewer than 23 registers are available you get Error 10. Similarly when using SOLVE uses 5 registers. I noticed when trying this on your excellent simulation that it doesn't matter how many registers are left in the common pool, integration and SOLVE always work.

Just add any function in the program memory. Reduce the common pool to 22 or fever registers, then try and integrate. It works fine, but on the original you should get an Error 10 message. 

I tested this on Android 9.

I realise that this is not really bug per se, but because your simulation is so excellent, it would be great if this behaviour was accurately included.

**Comment by zathras** [comment]
Published in 2.1.12
