### ISSUE TITLE
Can we go yet closer to real HP15C with RAN#?

### ISSUE THREAD

**Issue by pane** [zathras/jrpn#87]
**Is your feature request related to a problem? Please describe.**
No problem, just another unnecessary crazy request to get closer to real HP15C (and matching Torsten's simulator?)

**Describe the solution you'd like**
Using particular Seed in the RAN# function to match the real calculator results

**Describe any alternatives you've considered**
Keep the Random to be as it gets now

**Additional context**
Crawling through [CE Owner's Handbook](https://literature.hpcalc.org/items/2259) (pg 49) with HP15C CE and JRPN 2.1.12 on hand revealed differences in RAN# function.
It seems possible to use the original formula for RAN# and it looks like Torsten is using it in his [emulator](https://hp-15c.hier-im-netz.de/homepage.htm).
Good summary with helpful links is here:
[hp-15c random number simulator](https://www.jepspectro.com/htmDoc/Random6.htm)
Probably not enough stock precision in Dart for plain implementation of the formula:
Seed(n+1) = FRAC(15743.52261*(100000*Seed(n)) + 0.1017980433)
but still feasible.

**Disclaimer**
Please feel free to skip this crazy suggestion, I think the real application is only when testing existing programs using RAN# with known seed (or to satisfy some underpinning motivation force to get as close as possible - although I guess that without all subtle twists to general algorithms, which are probably not documented and if so not publicly available - it is not possible to make 100% match anyhow. If it is required than emulators should be used instead.

KR
P

**Comment by zathras** [comment]
Yeah, this one feels out of scope to me.  As a rule, I don't go out of my way to provide _worse_ results than the build in libraries I'm using, and I'm pretty confident that Dart's default random number generator is substantially better than the old 15C's.  The Solve and Integrate functions are like this too -- I used a modern algorithm for both that's probably better than what they could reasonably implement under the severe hardware and power constraints forty years ago.

Decimal addition and subtraction are a different matter.  For a calculator that presents its answers to humans using decimal, avoiding counter-intuitive base-2 rounding behavior is an improvement.

To get exactly the 15C's behavior for everything, the right answer is to emulate the hardware, and run the original code from the ROM.  There are emulators that do this.

**Comment by pane** [comment]
Totally agree. P

**Comment by zathras** [comment]
From #124:
> Side note: ... I would find more useful if there is an option/switch to select between either "Dart RND" or HP RND" generator sequence since you can verify the code correctness when using particular seed - this could be helpful in some instances to keep this fidelity with the real15C.

Is the algorithm used by the real 15C even available in a place that isn't copyrighted, or that isn't itself violating copyright?  I do keep the JRPN calculators clean room -- I haven't looked at the original calculator's firmware, and I've stayed away from any descriptions of the internal functioning from people who have.  Not knowing the 15C's algorithm, I can't duplicate it!

**Comment by pane** [comment]
Fair enough.
KR
P
