### ISSUE TITLE
Leading 0's (Flag #3) should be shown when entering digits in HEX,BIN,OCT modes

### ISSUE THREAD

**Issue by meltdown03** [zathras/jrpn#89]
**JRPN 16C or 15C?**
16C
**Describe the bug**
On the actual device, the leading 0's are visible all the time, even when entering new numbers. The 0's change to the new number. The `.` (decimal point in front of mode letter) is also visible if the wordsize expands beyond the current window.

**To Reproduce**
Set flag 3 and a word size that word expose leading 0's based on the current mode, not including `DEC`.
Enter a number and the leading 0's disappear.

**Expected behavior**
The leading 0's and the `.` indicating more windows should be visible during digit entry. 

**Platform:**
Android (Beta)
Linux build from latest source

**Additional context**
Pages 47 and 49 of the manual show flag 3 set and show the leading 0's

**Comment by zathras** [comment]
Makes sense.  I'd call this more of an enhancement.  I tend to reserve "bug" for issues that cause incorrect results or other errors.  This is kind of borderline maybe, but mostly cosmetic.

**Comment by meltdown03** [comment]
I wasn't sure what to label it. It does make it easier to enter digits
knowing how many places are left to go. Feel free to relabel it though.

**Comment by zathras** [comment]
@meltdown03  If you are entering digits, and so far you have entered, say, 1111 in 16 bit binary mode, does the display show "00001111 .b" or "00001111 b"?  The description makes it sound like the former, but I want to be sure.

**Comment by meltdown03** [comment]
It has the dot if the word size is larger than the window, yes.

**Comment by meltdown03** [comment]
This is in 16 bit wordsize
![20240330_104045](https://github.com/zathras/jrpn/assets/6166536/26e592b9-d0cf-4611-83b9-15810fa12e32)

**Comment by zathras** [comment]
OK, I think that does it.  Could you give it a test drive?  Do you need a build for that, and if so, for what platform?  (If need be, I can just publish a beta to the web.)

**Comment by meltdown03** [comment]
I built it for android and it works like expected. The leading 0's and dot
are there like they should be on digit entry.
