### ISSUE TITLE
Show Calculator internals

### ISSUE THREAD

**Issue by ljgww** [zathras/jrpn#91]
want to see calculator internals screen

how to reach it?

running simulator on linux

**Comment by zathras** [comment]
It's in the menu.  Click the three dots in the upper-right hand corner of the screen.

**Comment by ljgww** [comment]
> It's in the menu. Click the three dots in the upper-right hand corner of the screen.

Thanks - Found it under Help section of the menu. Perhaps this can be noted in the documentation.
Did not see this option before. Will check another PC as to why I did not see it, perhaps it is different version. It could be just me not noticing.
At any rate thank you for the quick response.
