### ISSUE TITLE
16C STATUS unsigned 0 vs U

### ISSUE THREAD

**Issue by ricknun** [zathras/jrpn#93]
**JRPN 16C or 15C?**
JRPN 16C

**Describe the bug**
STATUS unsigned is displayed at "U" and the real 16C displays it as "0". (A minor issue but not true to the original.)

**To Reproduce**
ON CLR BSP UNSGN STATUS

**Platform:**
Windows 10

**Comment by ricknun** [comment]
> you meant "U-32-0000" should be "0-32-0000" here?
Correct, and thanks for the quick response!

**Comment by zathras** [comment]
It's a one-character fix in the source :-)

**Comment by zathras** [comment]
Released in 2.1.14
