### ISSUE TITLE
16C WINDOW 1 error

### ISSUE THREAD

**Issue by ricknun** [zathras/jrpn#94]
**JRPN 16C or 15C?**
JRPN 16C

**Describe the bug**
A "WINDOW 1" program instruction can cause the display of WINDOW 0.

**Debug Log**
Ask if desired, but this program takes 3.5 hours to run on a real HP-16C.

**To Reproduce**
Running my HP-16C "e to 400 decimal places" program at
https://www.hpmuseum.org/forum/thread-3017.html
leads to a WINDOW error on JRPN 16C.  I tried to reduce the problem to a simpler program and failed.  The following complete run of the program will replicate it.

ON CLR BSP (simulator reset)
Menu, Settings, System Settings, 0 ms/Program Instruction.
Import Program e400a_no_PSE.16c.
DEC UNSGN 56 WSIZE 1 STO 0 24 STO I (capital I) 214 ABS GSB E
This calculates e to 400 decimal places in binary instantly.  It takes 3.5 hours on a real 16C.

Import program e400b.16c.
1 STO I (capital I) 10000000000000000 (10^16) STO 0 0 ENTER GSB D
This converts e to decimal, 16 digits at a time.

BUG: 84590452 is displayed, WINDOW 0 of the first 16 digits of frac(e) = 7182818284590452 that is currently in Rx.  But WINDOW 1 should be displayed (71828182) in response to where the program stopped at e400b.16c line 024 (WINDOW 1).

Entering WINDOW 1 shows the desired correct "71828182".
Entering WINDOW 0 shows the desired correct "84590452".
But the program did WINDOW 0 in response to the WINDOW 1 instruction.

**Platform:**
Windows 10
[e400a_no_PSE.txt](https://github.com/zathras/jrpn/files/15113448/e400a_no_PSE.txt)
[e400b.txt](https://github.com/zathras/jrpn/files/15113449/e400b.txt)

**Comment by zathras** [comment]
Hmmm...  I suspect something isn't right with WINDOW generally, when executed as part of a program, when in window mode (as opposed to Grow LCD mode).  I don't see any reason why it wouldn't be reproducible with a simpler program, like entering FF00, going to binary mode, and then doing WINDOW 1 programmatically.  I'll have to give that a try.  Maybe I'm just resetting window to 0 when the calculator comes out of running mode, or something like that.

I might add a regression test based on this program...  I like the idea of the Github server calculating e this way every time I do a commit :-)

**Comment by ricknun** [comment]
I tried to replicate it with this program, looking at various values in the display.  But it always seemed to work.
[WINDOW_1_0.txt](https://github.com/zathras/jrpn/files/15119633/WINDOW_1_0.txt)

**Comment by ricknun** [comment]
Details: I tried WINDOW_1_0.16c with 56-bit word size, UNSGN, DEC, and 16-digit values like 1234567890123456 in Rx, like the "e" program does.  That seems to work as expected instead of showing the problem.

**Comment by zathras** [comment]
Ha!  Yes, it works fine with PSE.  But change PS to R/S, and you'll find it doesn't work.

That give me a pretty strong clue where the bug is.

**Comment by zathras** [comment]
Yep, and the fix is pretty safe -- nothing too complicated going on here.  https://github.com/zathras/jrpn/commit/d7ce1fedd0cd85551f2df09b31efb0c7e178d5a4

@ricknun, are you planning to do more paying around/testing in the near future?  And, is there much urgency from your side?  Typically I like to batch up a few bugs before I spin a release.  With six targeted platforms, doing a release is a bit tedious!

Let me know if you want a windows EXE in the meantime.

**Comment by zathras** [comment]
Good point about extra memory -- see #95.

If you do find new bugs, feel free to submit new github issues.  That helps a bit with tracking, and is a convenient hook for the change log.

BTW, I became WN6POY in 1976, and I soldered together an HW-101 back then.  Now I'm AG6B, though not active.

**Comment by zathras** [comment]
Released in 2.1.14
