### ISSUE TITLE
Allow additional memory

### ISSUE THREAD

**Issue by zathras** [zathras/jrpn#95]
From #94, it was suggested that allowing a larger memory would be interesting to have.  Initially I didn't do this; the main goal was to make a faithful simulation, not a better 16C.  But for the 16C especially, I can see how extra memory is worth doing; there aren't that many RPN programmers calculators around.  (For the 15C it's maybe less interesting, since there are many more powerful RPN scientific calculators, and scientific calculator simulators around.)

There's no particular upper limit to memory size, though I guess over 1 MB or so some things might slow down noticeably.  But if someone configures a Giga-nybble of memory, they really shouldn't be surprised by that!

A setting just under the program instruction delay allowing extra nybbles of memory would do this.  I'll need to be a little careful to make sure that nothing bad happens, like a negative number of available registers when memory is taken away.

**Comment by zathras** [comment]
On the 15C, DIM (i) (setting the # of registers) will need some attention.  As to checking that the memory isn't made to small for the current program size, I guess a simple, robust thing to do would be to check `availableRegisters` with the new size, and if the result is too small (<2 on the 15C, and I guess <0 on the 16C), I could make an error dialog, and expect the user to clear program memory if necessary.

**Comment by zathras** [comment]
> A reasonable extra memory limit is 406 64-bit (max WSIZE) registers = 3248 bytes = 16 times the real HP-16C. This makes the fixed-size special index register have the same limits as the real 16C.

I can see that.  OTOH something like 1 mega-nybble is bigger than anyone should ever want, and small enough to be well short of any real resource constraint, probably by a couple of orders of magnitude.  I guess that would make the maximum number of 64 bit num registers on the 16C be 65,536, which is a nice round number.

I will have to make sure that the status display (g-MEM on 15C) doesn't do anything silly.

**Comment by zathras** [comment]
Hi @ricknun, I went ahead and implemented this, with the 1 mega-nybble limit.  I guess "GTO .xxx" isn't much help with a 100,000 line program, but I can't think of anything that actually breaks.

If you want to try it out  with more memory for some bigger programs, here's a .zip file with a Windows executable.  Just unzip it, and click on the .exe at the top level.  This is really just an unsigned msix that I've renamed.  If you're set up to build from source, let me know.

And thanks for all the testing you're doing!

![Screenshot 2024-04-27 at 2 15 05 PM](https://github.com/zathras/jrpn/assets/20762139/f55adee9-3f4f-406c-8ba1-806b3eda899b)
[jrpn16_windows_build.zip](https://github.com/zathras/jrpn/files/15140042/jrpn16_windows_build.zip)

**Comment by ricknun** [comment]
Great! Attached is an e to 7800 digits program, my memory config, and the first 18 digits of frac(e).  Each press of R/S gives 18 more digits.  It took 53 seconds runtime on my Windows 10 Intel Core i7-10700 2.9 GHz CPU. Another useful feature now would be a way to output the display value every PSE instruction, to capture all 7800 digits in a file. 
[e7800.txt](https://github.com/zathras/jrpn/files/15140281/e7800.txt)
![e7800a](https://github.com/zathras/jrpn/assets/6921857/4d30c791-d46f-4f06-b7da-2de46fc17371)
![e7800b](https://github.com/zathras/jrpn/assets/6921857/1fd48d99-967f-4654-b34b-0aff417f6bb8)

**Comment by ricknun** [comment]
A correction -- e7800.16c displays 19 digits at a time (not 18).  To run the program set 0 ms/Program Instruction, 12992 Total memory, and GSB A.

**Comment by zathras** [comment]
Fun!  42 seconds on my Mac Mini.

**Comment by pane** [comment]
> If you want to try it out with more memory for some bigger programs, here's a .zip file with a Windows executable. Just unzip it, and click on the .exe at the top level. This is really just an unsigned msix that I've renamed. If you're set up to build from source, let me know.
> 

Hi Zathars,
Although it is very reasonable explanation that HP15C memory extension was not a project goal, it seems to be carried along with 16C engine expansion. Do you happen to have win version of 15C with expanded memory?
Thank you for constant improvements.
KR
P

**Comment by zathras** [comment]
> Do you happen to have win version of 15C with expanded memory?

Sure.  I'll be doing a real release before too long, so let me know if you discover anything from this version.

[jrpn15_windows_build.zip](https://github.com/zathras/jrpn/files/15153288/jrpn15_windows_build.zip)

**Comment by pane** [comment]
> Sure. I'll be doing a real release before too long, so let me know if you discover anything from this version.

I am sorry, but still busy with other duties and did not have a chance to look at new features and memory expansion.
KR
P

**Comment by zathras** [comment]
Released in 2.1.14
